<center><span style="font-size:50px;"><b>INITIAL ANALYSIS</b></span></center>

---

---

---

---

<center><span style="font-size:30px;"><b>UPLOADING DATA</b></span></center>

In [1]:
import pandas as pd

# files to upload
files = [   "data/earthquakes_italy_1990-1995.csv",
            "data/earthquakes_italy_1995-2000.csv",
            "data/earthquakes_italy_2000-2005.csv",
            "data/earthquakes_italy_2005-2010.csv",
            "data/earthquakes_italy_2010-2020.csv",
            "data/earthquakes_italy_2020-2026.csv"
        ]

df_list = []

for file in files:
    df_partial = pd.read_csv(file)
    df_list.append(df_partial)

# merge dataframes
df_raw = pd.concat(df_list, ignore_index=True)

Let's observe the obtained dataframe:

In [2]:
print(f"The uploaded dataframe has {len(df_raw):_} rows and {len(df_raw.columns):_} columns.")
memory = df_raw.memory_usage(deep=True).sum() / (1024 ** 2)
print(f"It occupies {memory:_.2f} MB in RAM memory")

display( pd.concat([df_raw.head(3),df_raw.tail(3)]) )

The uploaded dataframe has 43_470 rows and 22 columns.
It occupies 29.27 MB in RAM memory

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,1990-01-01T03:25:58.270Z,44.3840,7.3120,10.000,1.6,ml,NaN,NaN,NaN,0.00,...,2014-11-07T00:45:26.432Z,"2 km SSW of Monterosso Grana, Italy",earthquake,NaN,NaN,NaN,NaN,reviewed,us,gen
1,1990-01-01T06:34:04.000Z,41.7140,19.4310,10.000,3.3,ml,NaN,NaN,NaN,1.20,...,2014-11-07T00:45:26.440Z,"17 km SW of Shëngjin, Albania",earthquake,NaN,NaN,NaN,NaN,reviewed,us,sko
2,1990-01-01T16:38:24.410Z,46.8010,9.7380,5.000,3.1,ml,NaN,NaN,NaN,1.30,...,2014-11-07T00:45:26.932Z,"5 km ENE of Arosa, Switzerland",earthquake,NaN,NaN,NaN,NaN,reviewed,us,grf
43467,2026-04-03T06:51:16.193Z,39.5749,20.6416,10.000,4.3,mb,48.0,46.0,1.426,0.84,...,2026-04-03T14:31:17.520Z,"16 km NE of Paramythiá, Greece",earthquake,5.56,1.884,0.133,16.0,reviewed,us,us
43468,2026-04-04T16:24:22.657Z,39.6618,20.5776,23.533,4.1,mb,44.0,46.0,1.506,0.91,...,2026-04-04T18:23:35.040Z,"13 km WSW of Rodotópi, Greece",earthquake,4.21,5.355,0.093,34.0,reviewed,us,us
43469,2026-04-06T04:20:50.717Z,39.7119,20.7070,10.000,4.6,mwr,35.0,62.0,1.425,0.99,...,2026-04-06T04:36:12.040Z,"1 km WNW of Rodotópi, Greece",earthquake,3.50,1.906,0.053,34.0,reviewed,us,us

In [3]:
print("\nCOLUMNS:")
print(df_raw.columns)

COLUMNS:
Index(['time', 'latitude', 'longitude', 'depth', 'mag', 'magType', 'nst',
       'gap', 'dmin', 'rms', 'net', 'id', 'updated', 'place', 'type',
       'horizontalError', 'depthError', 'magError', 'magNst', 'status',
       'locationSource', 'magSource'],
      dtype='object')

Meaning of the less obvious comlumns (the majority are useless to us):
* depth: Depth of the earthquake in kilometers (km).
* mag: Magnitude of the earthquake
* magType: Type of magnitude used. (maybe we should confront only earthquake with same magtype?)
* nst: Number of seismic stations that reported the event.
* gap: Largest azimuthal gap in station coverage (degrees).
* dmin: Distance to the nearest station (in degrees).
* rms: Root mean square of the travel time residuals (in seconds).
* net: Network that detected the event (e.g., us, ci, hv). It identifies the organization or seismic network responsible.
* id: The unique identifier for the earthquake event. It’s usually a string combining the net code and a unique event code.
* updated: Time the event information was last updated.
* place: Human-readable location (e.g., "10km SE of Town X").
* type: Type of seismic event (earthquake, quarry blast, etc.). But I only downloaded earthquakes so this column should be useless.
* horizontalError: Horizontal location error (in km or m).
* depthError: Error estimate for the depth (in km).
* magError: Error estimate for the magnitude.
* magNst: Number of stations used for magnitude calculation.
* status: Review status of the event (reviewed, automatic). It means whether the data has been automatically generated or manually reviewed by a seismologist.
* locationSource: Agency that determined the location.
* magSource: Agency that determined the magnitude.

---

---

---

---

<center><span style="font-size:30px;"><b>FILTERING DATA</b></span></center>

Let's keep only earthquakes happened in Italy and only useful columns:

In [8]:
# Keep only the useful columns
df_filtered = df_raw[['time', 'latitude', 'longitude', 'depth', 'mag', 'place']]

# Filter rows where 'place' contains the word "Italy" (case-insensitive)
mask = df_filtered['place'].str.contains("Italy", case=False, na=False)

# Apply the filter to the reduced dataframe
df = df_filtered[mask].reset_index(drop=True)

In [10]:
print(f"The uploaded dataframe has {len(df):_} rows and {len(df.columns):_} columns.")
memory = df.memory_usage(deep=True).sum() / (1024 ** 2)
print(f"It occupies {memory:_.2f} MB in RAM memory")

display( pd.concat([df.head(5),df.tail(5)]) )

The uploaded dataframe has 19_264 rows and 6 columns.
It occupies 3.36 MB in RAM memory

,time,latitude,longitude,depth,mag,place
0,1990-01-01T03:25:58.270Z,44.3840,7.3120,10.000,1.6,"2 km SSW of Monterosso Grana, Italy"
1,1990-01-01T18:19:32.100Z,45.0370,7.3020,10.000,2.3,"1 km S of Coazze, Italy"
2,1990-01-01T18:46:01.200Z,44.4150,8.1120,10.000,1.7,"2 km WSW of Camerana, Italy"
3,1990-01-01T19:50:17.150Z,44.3220,7.4520,10.000,1.7,"2 km WNW of Roccavione, Italy"
4,1990-01-02T00:15:03.150Z,44.3660,7.1730,10.000,1.6,"5 km SSW of Campomolino, Italy"
19259,2026-03-13T08:54:59.086Z,40.7276,15.4985,10.000,2.2,"3 km SSE of Muro Lucano, Italy"
19260,2026-03-21T01:46:05.619Z,38.4955,14.3678,10.000,5.2,"40 km W of Leni, Italy"
19261,2026-03-21T01:49:10.169Z,38.5003,14.3653,10.000,4.3,"40 km W of Leni, Italy"
19262,2026-03-21T18:04:58.392Z,38.0790,14.5935,60.858,4.1,"2 km NNE of Acquedolci, Italy"
19263,2026-03-26T08:40:30.776Z,44.0376,10.9974,72.371,4.2,"6 km WNW of Cantagallo, Italy"